services:

  redis:
    image: docker.dragonflydb.io/dragonflydb/dragonfly:latest

  migrate:
    build: .
    command: python manage.py migrate --noinput
    env_file: .env
    volumes:
      - .:/app
      - venv:/app/.venv
    environment:
      DJANGO_SETTINGS_MODULE: p2.core.settings

  collectstatic:
    build: .
    command: python manage.py collectstatic --noinput
    env_file: .env
    volumes:
      - .:/app
      - venv:/app/.venv
    environment:
      DJANGO_SETTINGS_MODULE: p2.core.settings
    depends_on:
      migrate:
        condition: service_completed_successfully

  web:
    build: .
    command: ["granian", "--interface", "asginl", "--host", "0.0.0.0", "--port", "8000", "--loop", "uvloop", "--workers", "8", "--runtime-mode", "mt", "--runtime-threads", "2", "--backpressure", "2048", "--no-ws", "--log", "--log-level", "error", "p2.core.asgi:application"]
    env_file: .env
    volumes:
      - .:/app
      - venv:/app/.venv
      - media:/app/media
      - ./storage:/storage
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: p2.core.settings
      P2_REDIS__HOST: redis
      REDIS_URL: redis://redis:6379/0
      ARQ_REDIS_URL: redis://redis:6379/1
    depends_on:
      collectstatic:
        condition: service_completed_successfully
      redis:
        condition: service_started


  worker:
    build: .
    command: ["python", "-m", "arq", "p2.core.worker.WorkerSettings"]
    env_file: .env
    volumes:
      - .:/app
      - venv:/app/.venv
      - media:/app/media
      - ./storage:/storage
    environment:
      DJANGO_SETTINGS_MODULE: p2.core.settings
      P2_REDIS__HOST: redis
      REDIS_URL: redis://redis:6379/0
      ARQ_REDIS_URL: redis://redis:6379/1
    depends_on:
      collectstatic:
        condition: service_completed_successfully
      redis:
        condition: service_started

  grpc:
    build: .
    command: ["python", "manage.py", "grpc"]
    env_file: .env
    volumes:
      - .:/app
      - venv:/app/.venv
      - media:/app/media
      - ./storage:/storage
    ports:
      - "50051:50051"
    environment:
      DJANGO_SETTINGS_MODULE: p2.core.settings
      P2_REDIS__HOST: redis
      REDIS_URL: redis://redis:6379/0
      ARQ_REDIS_URL: redis://redis:6379/1
    depends_on:
      collectstatic:
        condition: service_completed_successfully
      redis:
        condition: service_started

volumes:
  media:
  venv:
