# Generated by Django 6.0.3 on 2026-03-29 22:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('name', models.TextField()),
                ('controller_path', models.TextField(choices=[('p2.core.storages.null.NullStorageController', 'NullStorageController'), ('p2.storage.local.controller.LocalStorageController', 'LocalStorageController'), ('p2.storage.s3.controller.S3StorageController', 'S3StorageController')])),
            ],
            options={
                'verbose_name': 'Storage',
                'verbose_name_plural': 'Storages',
                'permissions': (('use_storage', 'Can use storage'),),
            },
        ),
        migrations.CreateModel(
            name='Volume',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('name', models.SlugField(max_length=63, unique=True)),
                ('space_used_bytes', models.BigIntegerField(default=0)),
                ('public_read', models.BooleanField(default=False)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2_core.storage')),
            ],
            options={
                'verbose_name': 'Volume',
                'verbose_name_plural': 'Volumes',
                'permissions': (('list_volume_contents', 'Can List contents'), ('use_volume', 'Can Use Volume')),
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('controller_path', models.TextField(choices=[('p2.components.image.controller.ImageController', 'ImageController'), ('p2.components.quota.controller.QuotaController', 'QuotaController'), ('p2.components.public_access.controller.PublicAccessController', 'PublicAccessController'), ('p2.components.replication.controller.ReplicationController', 'ReplicationController'), ('p2.components.expire.controller.ExpiryController', 'ExpiryController')])),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2_core.volume')),
            ],
            options={
                'verbose_name': 'Component',
                'verbose_name_plural': 'Components',
                'unique_together': {('volume', 'controller_path')},
            },
        ),
        migrations.CreateModel(
            name='VolumeACL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(default=list)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('volume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acls', to='p2_core.volume')),
            ],
            options={
                'indexes': [models.Index(fields=['volume', 'user'], name='p2_core_vol_volume__27e49d_idx'), models.Index(fields=['volume', 'group'], name='p2_core_vol_volume__ed0345_idx')],
                'unique_together': {('volume', 'group'), ('volume', 'user')},
            },
        ),
    ]
