# Generated by Django 6.0.3 on 2026-03-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_core', '0031_data_remove_old_hashes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='volumeacl',
            new_name='p2_core_vol_volume__27e49d_idx',
            old_name='p2_core_vol_volume__user_idx',
        ),
        migrations.RenameIndex(
            model_name='volumeacl',
            new_name='p2_core_vol_volume__ed0345_idx',
            old_name='p2_core_vol_volume_group_idx',
        ),
        migrations.AddIndex(
            model_name='blob',
            index=models.Index(fields=['volume', 'prefix'], name='p2_core_blo_volume__ea349f_idx'),
        ),
    ]
