# Generated by Django 6.0.3 on 2026-03-25 22:01

import p2.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p2_api', '0004_data_encrypt_secret_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='access_key',
            field=models.CharField(default=p2.api.models.get_access_key, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
