# Generated by Django 6.0.3 on 2026-03-29 22:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServeRule',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('name', models.TextField()),
                ('blob_query', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
