# Generated by Django 6.0.3 on 2026-03-29 22:16

import django.core.serializers.json
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogAdaptor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('tags', models.JSONField(blank=True, default=dict)),
                ('name', models.TextField()),
                ('controller_path', models.TextField(choices=[('p2.log.controllers.database.DatabaseLogController', 'DatabaseLogController')])),
            ],
            options={
                'verbose_name': 'Log Adaptor',
                'verbose_name_plural': 'Log Adaptors',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('request_uid', models.UUIDField(blank=True, null=True)),
                ('body', models.JSONField(default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('adaptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='p2_log.logadaptor')),
            ],
            options={
                'verbose_name': 'Log Record',
                'verbose_name_plural': 'Log Records',
            },
        ),
    ]
