# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: serve.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'serve.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bserve.proto\x12\x02p2\"\x8c\x01\n\x0cServeRequest\x12\x0f\n\x07session\x18\x01 \x01(\t\x12\x0b\n\x03url\x18\x02 \x01(\t\x12.\n\x07headers\x18\x03 \x03(\x0b\x32\x1d.p2.ServeRequest.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x9b\x01\n\nServeReply\x12\x0f\n\x07session\x18\x01 \x01(\t\x12\x10\n\x08matching\x18\x02 \x01(\x08\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12,\n\x07headers\x18\x04 \x03(\x0b\x32\x1b.p2.ServeReply.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32;\n\x05Serve\x12\x32\n\x0cRetrieveFile\x12\x10.p2.ServeRequest\x1a\x0e.p2.ServeReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'serve_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SERVEREQUEST_HEADERSENTRY']._loaded_options = None
  _globals['_SERVEREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_SERVEREPLY_HEADERSENTRY']._loaded_options = None
  _globals['_SERVEREPLY_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_SERVEREQUEST']._serialized_start=20
  _globals['_SERVEREQUEST']._serialized_end=160
  _globals['_SERVEREQUEST_HEADERSENTRY']._serialized_start=114
  _globals['_SERVEREQUEST_HEADERSENTRY']._serialized_end=160
  _globals['_SERVEREPLY']._serialized_start=163
  _globals['_SERVEREPLY']._serialized_end=318
  _globals['_SERVEREPLY_HEADERSENTRY']._serialized_start=114
  _globals['_SERVEREPLY_HEADERSENTRY']._serialized_end=160
  _globals['_SERVE']._serialized_start=320
  _globals['_SERVE']._serialized_end=379
# @@protoc_insertion_point(module_scope)
