# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from p2.grpc.protos import serve_pb2 as serve__pb2


class ServeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        self.RetrieveFile = channel.unary_unary(
                '/p2.Serve/RetrieveFile',
                request_serializer=serve__pb2.ServeRequest.SerializeToString,
                response_deserializer=serve__pb2.ServeReply.FromString,
                _registered_method=True)


class ServeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RetrieveFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RetrieveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveFile,
                    request_deserializer=serve__pb2.ServeRequest.FromString,
                    response_serializer=serve__pb2.ServeReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_service_handler(
            'p2.Serve', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


class Serve(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RetrieveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p2.Serve/RetrieveFile',
            serve__pb2.ServeRequest.SerializeToString,
            serve__pb2.ServeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
