/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CreateFolderDialog: typeof import('./src/components/CreateFolderDialog.vue')['default']
    FilePreview: typeof import('./src/components/FilePreview.vue')['default']
    ObjectDetails: typeof import('./src/components/ObjectDetails.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadDialog: typeof import('./src/components/UploadDialog.vue')['default']
  }
}
